version: '3.0'
services:
  minecraft-server:
    container_name: minecraft-server
    build: src
    volumes:
      - "./data:/app"
    ports:
      - "25565:25565"
    environment:
      - MC_RAM=2G
      - server.jar-url=
      - UID=1000 
      - GID=1000
    stdin_open: true
    tty: true
    restart: unless-stopped
